"""baseline

Revision ID: 69190266b045
Revises:
Create Date: 2026-05-25 03:59:43.366812

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69190266b045"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organism", sa.String(length=80), nullable=True),
        sa.Column("reference_genome", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "traces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("tokens_input", sa.Integer(), nullable=False),
        sa.Column("tokens_output", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_creation", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_read", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("awaiting_approval_plan", sa.JSON(), nullable=True),
        sa.Column("approval_reasons", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.create_index("ix_traces_project_created", ["project_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_traces_project_id"), ["project_id"], unique=False)

    op.create_table(
        "project_memory",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_project_memory_key"),
    )
    with op.batch_alter_table("project_memory", schema=None) as batch_op:
        batch_op.create_index("ix_project_memory_project_updated", ["project_id", "updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_memory", schema=None) as batch_op:
        batch_op.drop_index("ix_project_memory_project_updated")

    op.drop_table("project_memory")
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traces_project_id"))
        batch_op.drop_index("ix_traces_project_created")

    op.drop_table("traces")
    op.drop_table("projects")
    # ### end Alembic commands ###
