"""Enhanced methods draft for manuscript submission.

Extends the generic ``render_methods_report`` with four things that the generic version
deliberately omits (it stays minimal so it's always correct):

  1. Per-tool prose templates  — "on-target efficiency was scored using DeepCRISPR [2]"
                                  rather than "tool `score_guide_on_target` was run".
  2. Benchmark accuracy numbers — hardcoded constants pulled from the committed benchmark
                                  artifacts, never generated by an LLM.
  3. Mandatory accuracy caveats — injected verbatim and validated to survive the polish step.
  4. BibTeX citation block      — copy-paste into any reference manager.
  5. Supplementary parameter table — every parameter, ready for a Supplementary Methods.

Pipeline
--------
  RunManifest + AgentResult
        │  deterministic
  _fill_templates()   ← per-tool sentences, hardcoded benchmark constants
        │  optional
  _llm_polish()       ← language only; strict prompt forbids new/changed facts
        │  guard
  _grounding_guard()  ← reject if output introduces ungrounded numbers or drops caveats
        │
  MethodsDraft        ← paragraph | bibtex_block | param_table_md | warnings

Design rules (mirroring provenance.methods_report):
  - Pure function, no I/O, no network.
  - Every number in the output traces to either the run manifest (runtime data) or
    a hardcoded _BENCHMARK constant (committed, review-gated).  The LLM touches only prose style.
  - Where a tool is unknown, it is summarised generically (no invented accuracy claims).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from bioforge.provenance.research_object import RunManifest, ToolInvocation

if TYPE_CHECKING:
    from bioforge.agent.loop import AgentResult


# ---------------------------------------------------------------------------
# Hardcoded benchmark constants
# Every number here must match a committed benchmark artifact.  Change the artifact
# first, then update the constant — they are intentionally co-located so a reviewer
# can spot any divergence in a single diff.
# ---------------------------------------------------------------------------

_B = {
    # DeepCRISPR on-target efficiency (§14.14 / §13)
    "deepcrispr_ont": {
        "formatted": "Spearman\u00a0\u03c1\u00a0=\u00a00.130",
        "dataset": "Chari-2015 held-out set",
        "n": 1234,
        "caveat": (
            "cross-dataset efficiency prediction carries substantial uncertainty, "
            "consistent with Haeussler et al. 2016"
        ),
        "caveat_key": "cross-dataset efficiency",  # substring validated by grounding guard
    },
    # CFD off-target discrimination
    "cfd_oft": {
        "formatted": "\u03c1\u00a0=\u00a00.313",
        "dataset": "annotated off-target sites",
        "n": 717,
        "caveat": None,
    },
    # FORECasT / inDelphi edit-outcome profiles
    "forecast_nhej": {
        "formatted": "median\u00a0TVD\u00a0=\u00a00.546",
        "dataset": "K562 measured profiles",
        "n": 150,
        "caveat": (
            "model trained on K562 cells; "
            "edit-outcome profiles in other cell lines may differ"
        ),
        "caveat_key": "K562 cells",
    },
    # GIAB NA12878 variant-calling concordance
    "giab_vc": {
        "precision": "0.980",
        "recall": "1.000",
        "dataset": "GIAB truth set v4.2.1, NA12878 chr20:10\u201310.1\u00a0Mb",
        "n": 49,
        "caveat": (
            "this benchmark covers a 100\u00a0kb validation window "
            "and does not reflect genome-wide accuracy"
        ),
        "caveat_key": "100\u00a0kb validation window",
    },
    # AlphaFold pLDDT threshold (AlphaFold standard guidance — Jumper 2021)
    "alphafold_plddt": {
        "threshold": 70,
        "caveat": (
            "pLDDT scores reflect model confidence, not experimental validation; "
            "low-confidence regions should be interpreted cautiously"
        ),
        "caveat_key": "pLDDT scores reflect model confidence",
    },
}

# ---------------------------------------------------------------------------
# BibTeX registry — keyed by tool slug.
# Entries are deduplicated (first-seen order) in the final output.
# ---------------------------------------------------------------------------

_BIBTEX: dict[str, str] = {
    "bioforge": (
        "@misc{BioForge2025,\n"
        "  author       = {{BioForge Contributors}},\n"
        "  title        = {{BioForge}: An Agentic Bioinformatics Platform with Grounded {AI}},\n"
        "  year         = {2025},\n"
        "  howpublished = {\\url{https://github.com/itthj/bioforge}}\n"
        "}"
    ),
    "deepcrispr": (
        "@article{Chuai2018,\n"
        "  author  = {Chuai, Guohui and Ma, Han and Yan, Jifang and Chen, Man and Hong, Na\n"
        "             and Xue, Dongyu and Zhou, Chi and Zhu, Chenxin and Chen, Ke and Duan, Bin\n"
        "             and others},\n"
        "  title   = {{DeepCRISPR}: optimized {CRISPR} guide {RNA} design by deep learning},\n"
        "  journal = {Genome Biology},\n"
        "  volume  = {19},\n"
        "  pages   = {80},\n"
        "  year    = {2018},\n"
        "  doi     = {10.1186/s13059-018-1459-4}\n"
        "}"
    ),
    "doench2016": (
        "@article{Doench2016,\n"
        "  author  = {Doench, John G. and Fusi, Nicolo and Sullender, Meagan and others},\n"
        "  title   = {Optimized {sgRNA} design to maximize activity and minimize off-target\n"
        "             effects of {CRISPR-Cas9}},\n"
        "  journal = {Nature Biotechnology},\n"
        "  volume  = {34},\n"
        "  pages   = {184--191},\n"
        "  year    = {2016},\n"
        "  doi     = {10.1038/nbt.3437}\n"
        "}"
    ),
    "haeussler2016": (
        "@article{Haeussler2016,\n"
        "  author  = {Haeussler, Maximilian and Sch{\\\"o}nig, Kai and Eckert, Helge and others},\n"
        "  title   = {Evaluation of off-target and on-target scoring algorithms and\n"
        "             integration into the guide {RNA} selection tool {CRISPOR}},\n"
        "  journal = {Genome Biology},\n"
        "  volume  = {17},\n"
        "  pages   = {148},\n"
        "  year    = {2016},\n"
        "  doi     = {10.1186/s13059-016-1012-2}\n"
        "}"
    ),
    "forecast": (
        "@article{Allen2019,\n"
        "  author  = {Allen, Felicity and Crepaldi, Luca and Alsinet, Clara and others},\n"
        "  title   = {Predicting the mutations generated by repair of {Cas9}-induced\n"
        "             double-strand breaks},\n"
        "  journal = {Nature Biotechnology},\n"
        "  volume  = {37},\n"
        "  pages   = {64--72},\n"
        "  year    = {2019},\n"
        "  doi     = {10.1038/nbt.4317}\n"
        "}"
    ),
    "blast": (
        "@article{Altschul1990,\n"
        "  author  = {Altschul, Stephen F. and Gish, Warren and Miller, Webb and\n"
        "             Myers, Eugene W. and Lipman, David J.},\n"
        "  title   = {Basic local alignment search tool},\n"
        "  journal = {Journal of Molecular Biology},\n"
        "  volume  = {215},\n"
        "  pages   = {403--410},\n"
        "  year    = {1990},\n"
        "  doi     = {10.1016/S0022-2836(05)80360-2}\n"
        "}"
    ),
    "alphafold": (
        "@article{Jumper2021,\n"
        "  author  = {Jumper, John and Evans, Richard and Pritzel, Alexander and others},\n"
        "  title   = {Highly accurate protein structure prediction with {AlphaFold}},\n"
        "  journal = {Nature},\n"
        "  volume  = {596},\n"
        "  pages   = {583--589},\n"
        "  year    = {2021},\n"
        "  doi     = {10.1038/s41586-021-03819-2}\n"
        "}"
    ),
    "alphafold_db": (
        "@article{Varadi2022,\n"
        "  author  = {Varadi, Mihaly and Anyango, Stephen and Deshpande, Mandar and others},\n"
        "  title   = {{AlphaFold} Protein Structure Database: massively expanding the\n"
        "             structural coverage of protein-sequence space with high-accuracy models},\n"
        "  journal = {Nucleic Acids Research},\n"
        "  volume  = {50},\n"
        "  pages   = {D439--D444},\n"
        "  year    = {2022},\n"
        "  doi     = {10.1093/nar/gkab1061}\n"
        "}"
    ),
    "interpro": (
        "@article{Paysan-Lafosse2023,\n"
        "  author  = {Paysan-Lafosse, Typhaine and Blum, Matthias and Chuguransky, Sara\n"
        "             and others},\n"
        "  title   = {{InterPro} in 2022},\n"
        "  journal = {Nucleic Acids Research},\n"
        "  volume  = {51},\n"
        "  pages   = {D418--D427},\n"
        "  year    = {2023},\n"
        "  doi     = {10.1093/nar/gkac993}\n"
        "}"
    ),
    "primer3": (
        "@article{Untergasser2012,\n"
        "  author  = {Untergasser, Andreas and Cutcutache, Ioana and Koressaar, Triinu\n"
        "             and others},\n"
        "  title   = {{Primer3} -- new capabilities and interfaces},\n"
        "  journal = {Nucleic Acids Research},\n"
        "  volume  = {40},\n"
        "  pages   = {e115},\n"
        "  year    = {2012},\n"
        "  doi     = {10.1093/nar/gks596}\n"
        "}"
    ),
    "vep": (
        "@article{McLaren2016,\n"
        "  author  = {McLaren, William and Gil, Laurent and Hunt, Sarah E. and others},\n"
        "  title   = {The {Ensembl} Variant Effect Predictor},\n"
        "  journal = {Genome Biology},\n"
        "  volume  = {17},\n"
        "  pages   = {122},\n"
        "  year    = {2016},\n"
        "  doi     = {10.1186/s13059-016-0974-4}\n"
        "}"
    ),
    "giab": (
        "@article{Krusche2019,\n"
        "  author  = {Krusche, Peter and Trigg, Len and Boutros, Paul C. and others},\n"
        "  title   = {Best practices for benchmarking germline small-variant calls in\n"
        "             human genomes},\n"
        "  journal = {Nature Biotechnology},\n"
        "  volume  = {37},\n"
        "  pages   = {555--560},\n"
        "  year    = {2019},\n"
        "  doi     = {10.1038/s41587-019-0054-x}\n"
        "}"
    ),
    "musclev5": (
        "@article{Edgar2022,\n"
        "  author  = {Edgar, Robert C.},\n"
        "  title   = {{MUSCLE} v5 enables improved estimates of phylogenetic tree topology},\n"
        "  journal = {Nature Communications},\n"
        "  volume  = {13},\n"
        "  pages   = {6329},\n"
        "  year    = {2022},\n"
        "  doi     = {10.1038/s41467-022-34630-w}\n"
        "}"
    ),
}

# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class MethodsDraft:
    """Everything the scientist needs to paste into a manuscript + Supplementary Methods."""

    paragraph: str          # Validated methods paragraph — past tense, inline citations [1][2]…
    bibtex_block: str       # All cited entries concatenated — paste into .bib file
    param_table_md: str     # Markdown table for Supplementary Methods
    warnings: list[str] = field(default_factory=list)
    trace_id: str = ""


# ---------------------------------------------------------------------------
# Parameter extraction helpers
# ---------------------------------------------------------------------------

def _params_by_tool_order(result: AgentResult | None) -> list[dict[str, Any]]:
    """Return tool_input dicts aligned with manifest.tools (same tool-call order)."""
    if result is None:
        return []
    return [
        s.tool_input or {}
        for s in result.steps
        if s.type == "tool_call" and s.tool_name is not None
    ]


def _pv(value: Any, max_chars: int = 50) -> str:
    """Compact parameter value for the supplementary table."""
    s = str(value)
    if len(s) > max_chars:
        return f"{s[:max_chars]}… ({len(s)}\u00a0chars)"
    return s


# ---------------------------------------------------------------------------
# Citation registry — builds ordered cite list and [N] index
# ---------------------------------------------------------------------------

class _CitationList:
    def __init__(self) -> None:
        self._seen: dict[str, int] = {}  # key → 1-based index
        self._keys: list[str] = []

    def add(self, key: str) -> str:
        """Register a citation key and return its [N] mark."""
        if key not in self._seen:
            self._seen[key] = len(self._keys) + 1
            self._keys.append(key)
        return f"[{self._seen[key]}]"

    @property
    def bibtex_block(self) -> str:
        entries = [_BIBTEX[k] for k in self._keys if k in _BIBTEX]
        return "\n\n".join(entries)


# ---------------------------------------------------------------------------
# Grounding guard
# ---------------------------------------------------------------------------

# Small numbers (single digits) appear freely in prose without being benchmark facts.
_IGNORE_NUMS = {str(i) for i in range(10)}


def _grounding_guard(
    template_prose: str,
    llm_prose: str,
    mandatory_caveats: list[str],
) -> tuple[bool, list[str]]:
    """Return (valid, issues).  valid=True → LLM output is safe to use."""
    # Extract every multi-digit number and version-like string from template (ground truth)
    fact_nums = set(re.findall(r"\b\d{2,}\.?\d*\b", template_prose))
    fact_vers = set(re.findall(r"\bv\d[\d.]+\b", template_prose, re.I))
    fact_nums |= fact_vers

    issues: list[str] = []

    # 1. Numbers in LLM output must all exist in template facts
    for num in re.findall(r"\b\d{2,}\.?\d*\b|\bv\d[\d.]+\b", llm_prose, re.I):
        if num not in _IGNORE_NUMS and num not in fact_nums:
            issues.append(f"Ungrounded token in LLM output: {num!r}")

    # 2. Every mandatory caveat's key phrase must survive
    for caveat in mandatory_caveats:
        if caveat.lower() not in llm_prose.lower():
            issues.append(f"Missing mandatory caveat: {caveat[:60]!r}…")

    return (not issues), issues


# ---------------------------------------------------------------------------
# LLM prose polish
# ---------------------------------------------------------------------------

_POLISH_SYSTEM = (
    "You are a scientific editor improving the fluency of a computational methods section "
    "for a peer-reviewed manuscript. You ONLY improve sentence flow and tense consistency. "
    "You NEVER add, remove, or change any number, date, version string, database name, "
    "citation mark, or accuracy caveat. Return only the edited paragraph — no commentary."
)

_POLISH_USER = """\
Rewrite the following methods text as natural scientific prose in past tense. \
Improve fluency and sentence variety only. \
All numbers, version strings, citation marks, and accuracy caveats must be preserved exactly.

{prose}"""


async def _llm_polish(prose: str) -> str:
    """Call the Anthropic API for a language-only fluency pass.  Returns original on any error."""
    try:
        import anthropic
        from bioforge.config import settings

        client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
        msg = await client.messages.create(
            model="claude-haiku-4-5",  # cheapest model — language only, no reasoning needed
            max_tokens=1024,
            system=_POLISH_SYSTEM,
            messages=[{"role": "user", "content": _POLISH_USER.format(prose=prose)}],
        )
        return msg.content[0].text.strip()
    except Exception:
        return prose  # silent fallback — template prose is always valid


# ---------------------------------------------------------------------------
# Per-tool sentence builders
# ---------------------------------------------------------------------------
# Each returns (sentence | "", [bibtex_keys], [param_rows], [mandatory_caveats])
# sentence="" means this tool is skipped (meta tools, etc.)

type _SentenceResult = tuple[str, list[str], list[dict], list[str]]


def _tool_design_guides(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    bf = cites.add("bioforge")
    ver = inv.version or "unknown"
    target = params.get("sequence", "")
    pam = params.get("pam", "NGG")
    n_guides = params.get("n_results", "")
    target_desc = f" targeting a {len(target)}-nt input sequence" if target else ""
    n_desc = f" {n_guides} candidate guides were identified." if n_guides else ""
    sentence = (
        f"CRISPR guide RNA design{target_desc} (PAM:\u00a0{pam}) was performed using "
        f"BioForge\u00a0v{ver}\u00a0{bf}.{n_desc}"
    )
    rows = [
        {"Tool": "design_guides", "Parameter": "PAM", "Value": _pv(pam)},
    ]
    if n_guides:
        rows.append({"Tool": "design_guides", "Parameter": "guides returned", "Value": _pv(n_guides)})
    return sentence, [], rows, []


def _tool_score_on_target(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    b = _B["deepcrispr_ont"]
    dc = cites.add("deepcrispr")
    hae = cites.add("haeussler2016")
    threshold = params.get("threshold")
    filter_desc = f" Guides with efficiency score \u2265\u00a0{threshold}% were retained." if threshold else ""
    caveat = b["caveat"]
    sentence = (
        f"On-target efficiency was scored using DeepCRISPR\u00a0{dc} "
        f"(benchmark: {b['formatted']} vs {b['dataset']}, n\u00a0=\u00a0{b['n']}; "
        f"{caveat}\u00a0{hae}).{filter_desc}"
    )
    rows = [{"Tool": "score_guide_on_target", "Parameter": "benchmark", "Value": b["formatted"]}]
    if threshold:
        rows.append({"Tool": "score_guide_on_target", "Parameter": "efficiency threshold", "Value": _pv(threshold)})
    return sentence, ["deepcrispr", "haeussler2016"], rows, [b["caveat_key"]]


def _tool_find_offtargets(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    b = _B["cfd_oft"]
    doe = cites.add("doench2016")
    cutoff = params.get("cfd_cutoff")
    cutoff_desc = f" (CFD cutoff\u00a0<\u00a0{cutoff})" if cutoff else ""
    sentence = (
        f"Off-target risk was assessed using CFD scoring\u00a0{doe}"
        f"{cutoff_desc} "
        f"(benchmark: {b['formatted']}, n\u00a0=\u00a0{b['n']} {b['dataset']})."
    )
    rows = [{"Tool": "find_offtargets", "Parameter": "benchmark", "Value": b["formatted"]}]
    if cutoff:
        rows.append({"Tool": "find_offtargets", "Parameter": "CFD cutoff", "Value": _pv(cutoff)})
    return sentence, ["doench2016"], rows, []


def _tool_edit_outcome(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    b = _B["forecast_nhej"]
    fc = cites.add("forecast")
    caveat = b["caveat"]
    sentence = (
        f"NHEJ repair outcome profiles were predicted using FORECasT\u00a0{fc} "
        f"(benchmark: {b['formatted']} vs {b['dataset']}, n\u00a0=\u00a0{b['n']}; {caveat})."
    )
    rows = [{"Tool": "edit_outcome", "Parameter": "benchmark", "Value": b["formatted"]}]
    return sentence, ["forecast"], rows, [b["caveat_key"]]


def _tool_blast(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    bl = cites.add("blast")
    ver = inv.version or "unknown"
    program = params.get("program", "blastn").upper()
    db = params.get("database", "nt")
    evalue = params.get("evalue", "1e\u22125")
    sentence = (
        f"Sequence similarity searches were performed using NCBI\u00a0{program} "
        f"v{ver}\u00a0{bl} against the {db} database "
        f"(E-value threshold\u00a0{evalue}). "
        f"BLAST is a deterministic alignment algorithm; no statistical accuracy benchmark applies."
    )
    rows = [
        {"Tool": "blast", "Parameter": "program", "Value": _pv(program)},
        {"Tool": "blast", "Parameter": "database", "Value": _pv(db)},
        {"Tool": "blast", "Parameter": "E-value threshold", "Value": _pv(evalue)},
    ]
    return sentence, ["blast"], rows, []


def _tool_alphafold(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    af = cites.add("alphafold")
    afd = cites.add("alphafold_db")
    b = _B["alphafold_plddt"]
    caveat = b["caveat"]
    sentence = (
        f"Protein structure was retrieved from the AlphaFold Protein Structure "
        f"Database\u00a0{afd}\u00a0{af}. "
        f"Residues with pLDDT\u00a0<\u00a0{b['threshold']} were classified as low-confidence "
        f"and excluded from structural interpretation; {caveat}."
    )
    rows = [{"Tool": "fetch_alphafold_structure", "Parameter": "pLDDT threshold", "Value": str(b["threshold"])}]
    return sentence, ["alphafold", "alphafold_db"], rows, [b["caveat_key"]]


def _tool_interpro(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    ip = cites.add("interpro")
    sentence = f"Domain annotation was performed using InterPro\u00a0{ip}."
    return sentence, ["interpro"], [], []


def _tool_annotate_variant(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    # Variant annotation prose is assembled collectively for all variant tools;
    # individual lookups (clinvar, dbsnp, gnomad) contribute to the same sentence.
    b = _B["giab_vc"]
    vep = cites.add("vep")
    giab = cites.add("giab")
    sentence = (
        f"Variant consequences were predicted using Ensembl VEP\u00a0{vep}. "
        f"Pipeline accuracy was assessed against the {b['dataset']}: "
        f"precision\u00a0=\u00a0{b['precision']}, recall\u00a0=\u00a0{b['recall']} "
        f"(n\u00a0=\u00a0{b['n']} truth variants)\u00a0{giab}; {b['caveat']}."
    )
    rows = [
        {"Tool": "annotate_variant", "Parameter": "benchmark precision", "Value": b["precision"]},
        {"Tool": "annotate_variant", "Parameter": "benchmark recall", "Value": b["recall"]},
    ]
    return sentence, ["vep", "giab"], rows, [b["caveat_key"]]


def _tool_design_primers(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    p3 = cites.add("primer3")
    ver = inv.version or "unknown"
    sentence = (
        f"PCR primer pairs were designed using Primer3\u00a0v{ver}\u00a0{p3}. "
        f"Primer3 is a rule-based deterministic algorithm; no statistical accuracy benchmark applies."
    )
    rows = [{"Tool": "design_primers", "Parameter": "version", "Value": _pv(ver)}]
    return sentence, ["primer3"], rows, []


def _tool_align_msa(inv: ToolInvocation, params: dict, cites: _CitationList) -> _SentenceResult:
    bf = cites.add("bioforge")
    n_seqs = params.get("n_sequences", "")
    n_desc = f" ({n_seqs} sequences)" if n_seqs else ""
    sentence = (
        f"Multiple sequence alignment{n_desc} was performed via BioForge\u00a0{bf} "
        f"using MUSCLE or Biopython pairwise2 (deterministic; no accuracy benchmark applies)."
    )
    return sentence, [], [], []


def _tool_sequence_generic(tool: str, inv: ToolInvocation, cites: _CitationList) -> _SentenceResult:
    bf = cites.add("bioforge")
    label = tool.replace("_", " ")
    sentence = f"{label.capitalize()} was computed using BioForge\u00a0{bf} (deterministic)."
    return sentence, [], [], []


# Dispatch table: tool name → builder function
_TOOL_DISPATCH: dict[str, Any] = {
    "design_guides":             _tool_design_guides,
    "score_guide_on_target":     _tool_score_on_target,
    "find_offtargets":           _tool_find_offtargets,
    "edit_outcome":              _tool_edit_outcome,
    "blast":                     _tool_blast,
    "fetch_alphafold_structure": _tool_alphafold,
    "fetch_interpro":            _tool_interpro,
    "annotate_variant":          _tool_annotate_variant,
    "call_variants":             _tool_annotate_variant,   # same prose
    "parse_vcf":                 None,                     # skip — internal
    "design_primers":            _tool_design_primers,
    "align_msa":                 _tool_align_msa,
    # Deterministic sequence tools — generic one-liner
    "gc_content":         lambda inv, p, c: _tool_sequence_generic("gc_content", inv, c),
    "reverse_complement": lambda inv, p, c: _tool_sequence_generic("reverse_complement", inv, c),
    "translate":          lambda inv, p, c: _tool_sequence_generic("translate", inv, c),
    "find_orfs":          lambda inv, p, c: _tool_sequence_generic("find_orfs", inv, c),
    "codon_usage":        lambda inv, p, c: _tool_sequence_generic("codon_usage", inv, c),
    # Meta tools — skip
    "remember":     None,
    "read_files":   None,
    "list_files":   None,
    "upload_file":  None,
}


# ---------------------------------------------------------------------------
# Template filler
# ---------------------------------------------------------------------------

def _fill_templates(
    manifest: RunManifest,
    params_by_index: list[dict[str, Any]],
) -> tuple[str, _CitationList, list[dict], list[str]]:
    """Build the raw methods paragraph, citations, param table rows, and mandatory caveats."""
    cites = _CitationList()
    # BioForge is always citation [1]
    cites.add("bioforge")

    sentences: list[str] = []
    all_param_rows: list[dict] = []
    all_mandatory_caveats: list[str] = []
    seen_tools: set[str] = set()

    for i, inv in enumerate(manifest.tools):
        tool = inv.tool
        if tool in seen_tools:
            continue  # e.g. blast called twice — deduplicate in prose
        seen_tools.add(tool)

        params = params_by_index[i] if i < len(params_by_index) else {}
        builder = _TOOL_DISPATCH.get(tool)

        if builder is None:
            continue  # explicitly skipped tool

        sent, bib_keys, param_rows, caveats = builder(inv, params, cites)
        if sent:
            sentences.append(sent)
        # Register extra bibtex keys (builder may add them via cites.add() internally)
        for k in bib_keys:
            cites.add(k)  # idempotent if already added
        all_param_rows.extend(param_rows)
        all_mandatory_caveats.extend(caveats)

    if not sentences:
        # Fallback: no recognised tools
        bf = cites.add("bioforge")
        sentences.append(
            f"Analyses were performed using BioForge\u00a0{bf}. "
            "No per-tool benchmark accuracy numbers apply to the tools invoked in this run."
        )

    paragraph = " ".join(sentences)
    return paragraph, cites, all_param_rows, all_mandatory_caveats


# ---------------------------------------------------------------------------
# Param table formatter
# ---------------------------------------------------------------------------

def _format_param_table(rows: list[dict]) -> str:
    if not rows:
        return "_No structured parameters captured for this run._"
    headers = ["Tool", "Parameter", "Value"]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row.get(h, "") for h in headers) + " |")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def render_methods_draft(
    manifest: RunManifest,
    result: AgentResult | None = None,
    *,
    polish: bool = True,
    trace_id: str = "",
) -> MethodsDraft:
    """Generate an enhanced manuscript-ready methods draft from a run manifest.

    Parameters
    ----------
    manifest:
        The content-addressed run manifest (from ``build_run_manifest``).
    result:
        The ``AgentResult`` for the run, used to extract per-tool parameters.
        Pass ``None`` to generate provenance-only prose without parameter detail.
    polish:
        Whether to apply LLM prose polishing (default True).  Set False in tests
        or when the API key is unavailable.
    trace_id:
        Stamped onto the returned ``MethodsDraft`` for the caller's convenience.

    Returns
    -------
    MethodsDraft
        Contains the validated paragraph, BibTeX block, parameter table (Markdown),
        and any warnings from the grounding guard.
    """
    params_by_index = _params_by_tool_order(result)

    # Phase 1: deterministic template fill
    template_prose, cites, param_rows, mandatory_caveats = _fill_templates(
        manifest, params_by_index
    )

    warnings: list[str] = []
    final_prose = template_prose  # safe fallback

    # Phase 2: optional LLM polish
    if polish:
        llm_prose = await _llm_polish(template_prose)

        # Phase 3: grounding guard
        valid, issues = _grounding_guard(template_prose, llm_prose, mandatory_caveats)
        if valid:
            final_prose = llm_prose
        else:
            warnings.append(
                "LLM polish output failed grounding validation — using template prose directly."
            )
            for issue in issues:
                warnings.append(f"  \u2022 {issue}")

    return MethodsDraft(
        paragraph=final_prose,
        bibtex_block=cites.bibtex_block,
        param_table_md=_format_param_table(param_rows),
        warnings=warnings,
        trace_id=trace_id,
    )
